# Generated by Django 4.1.2 on 2022-12-27 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("income", "INCOME"),
                            ("fixed_expenses", "FIXED EXPENSES"),
                            ("personal_expenses", "PERSONAL EXPENSES"),
                            ("debt_expenses", "DEBT EXPENSES"),
                        ],
                        max_length=17,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("description", models.CharField(max_length=100)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
